---

- name: Fix dpkg
  shell: "dpkg --configure -a"

- name: Update All Packages
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes
    state: latest
  register: reboot_node

- name: Reboot system if required
  when: reboot_node is changed
  reboot:
    post_reboot_delay: 0
    reboot_timeout: 600

