---

- name: Create kube admin dir (ubuntu)
  file:
    dest: /home/ubuntu/.kube/
    owner: ubuntu
    group: ubuntu
    state: directory

- name: Copy kubeconfig
  copy:
    src: ../../../ignition/auth/kubeconfig
    dest: /home/ubuntu/.kube/config
    mode: 0640

- name: Copy oc client
  copy:
    src: ../../../openshift-client-linux-4.7.0-0.okd-2021-05-22-050008.tar.gz
    dest: /home/ubuntu/openshift-client-linux-4.7.0-0.okd-2021-05-22-050008.tar.gz
    mode: 0644

- name: Extract oc client
  unarchive:
    src: /home/ubuntu/openshift-client-linux-4.7.0-0.okd-2021-05-22-050008.tar.gz
    dst: /usr/local/bin

