---

- name: Install various support packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: present
  vars:
    packages:
    - make
    - net-tools
    - ntp
    - nginx
    - bind9
    - bind9utils

